require('plugins')
require('config.basic')
require('config.colorscheme')
require('config.indentation')
require('config.search')
require('config.visual')
require('config.file-handling')
require('config.behaviour')
require('config.cursor')
require('config.keymaps')
require('config.autocmd')
require('config.folding')
require('config.tabs')
require('config.cmd')
require('config.floatty')

require('lsp')
